stages:

  preprocessing:
    cmd: python scripts/run_stage.py src/preprocessing.py pipeline_preprocessing.done
    deps:
      - scripts/run_stage.py
      - src/preprocessing.py
      - src/db_connection.py
    outs:
      - pipeline_preprocessing.done

  feature_engineering:
    cmd: python scripts/run_stage.py src/feature_engineering.py pipeline_feature_engineering.done
    deps:
      - scripts/run_stage.py
      - src/feature_engineering.py
      - src/db_connection.py
      - pipeline_preprocessing.done
    outs:
      - pipeline_feature_engineering.done

  emotion_inference:
    cmd: python scripts/run_stage.py src/emotion_inference.py pipeline_emotion_inference.done
    deps:
      - scripts/run_stage.py
      - src/emotion_inference.py
      - src/db_connection.py
      - pipeline_feature_engineering.done
    outs:
      - pipeline_emotion_inference.done

  train:
    cmd: python scripts/run_stage.py src/train.py pipeline_train.done
    deps:
      - scripts/run_stage.py
      - src/train.py
      - src/db_connection.py
      - pipeline_emotion_inference.done
    outs:
      - pipeline_train.done

  evaluate:
    cmd: python scripts/run_stage.py src/evaluate.py pipeline_evaluate.done
    deps:
      - scripts/run_stage.py
      - src/evaluate.py
      - src/db_connection.py
      - pipeline_train.done